build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 10
  LargeClass:
    active: true
    threshold: 120
  LongMethod:
    active: true
    threshold: 30
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
    ignoreDefaultParameters: true
  MethodOverloading:
    active: true
    threshold: 3
  NestedBlockDepth:
    active: true
    threshold: 3
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 12
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 10

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '([a-z][a-zA-Z0-9]*)|(`.*`)'
    ignoreAnnotated: ['Composable']
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
    ignorePropertyDeclaration: true
  MaxLineLength:
    active: true
    maxLineLength: 100
  UnusedImports:
    active: true
  WildcardImport:
    active: false
  NullableBooleanCheck:
    active: true
  OptionalUnit:
    active: true
  UnnecessaryParentheses:
    active: true
